AllCops:
    Exclude:
        - 'Gemfile'
        - 'Rakefile'
        - 'bin/*'
        - 'spec/support/rails_app/**/*'
        - '**/*_pb.rb'

Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space

Metrics/BlockLength:
    ExcludedMethods:
        - describe
        - context
        - it

Metrics/ClassLength:
    Max: 150

Metrics/MethodLength:
    Max: 15

Metrics/LineLength:
    Max: 200

Style/BlockDelimiters:
    EnforcedStyle: braces_for_chaining

Style/Documentation:
    Exclude: ['**/*']

Style/YodaCondition:
    EnforcedStyle: require_for_equality_operators_only
